### ISSUE TITLE
repository naming 방식이에요.

### ISSUE THREAD

**Issue by yoonje** [iamhge/buddy-allocator#1]
https://stackoverflow.com/questions/11947587/is-there-a-naming-convention-for-git-repositories

**Comment by yoonje** [comment]
repo setting 가서 rename으로 이름 변경할 수 있고 이슈는 close 하면 사라집니다.

**Comment by iamhge** [comment]
헐 오빠 감사해요ㅋㅋㅋㅋㅋㅋ
깃 생초보자라^^..ㅎㅎㅎㅎ

2020년 1월 31일 (금) 오후 1:00, Yoonje Choi <notifications@github.com>님이 작성:

**Comment by yoonje** [comment]
Good !
